---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lls-provider-kft
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - pytorchjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
