name: Build and Publish Image to ghcr.io

on:
  push:
  pull_request:

jobs:
  build-and-publish:
    name: Build and Publish Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/kfto-remote-provider:amd64
            ghcr.io/${{ github.repository_owner }}/kfto-remote-provider:arm64
          push: true
